import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "./components/main-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"l-body " + inter.className}>
        <header className="l-header">
          <MainNav />
        </header>
        <main className="l-main">{children}</main>
        <footer className="l-footer"> Copyright © Noroff Education AS </footer>
      </body>
    </html>
  );
}
