import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Link from "next/link";
import { FiInstagram, FiFacebook, FiLinkedin, FiMail } from "react-icons/fi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const socialLinks = [
    {
      Icon: <FiInstagram />,
      href: "https://www.instagram.com/",
      label: "Instagram",
    },
    {
      Icon: <FiFacebook />,
      href: "https://www.instagram.com/",
      label: "Facebook",
    },
    {
      Icon: <FiLinkedin />,
      href: "https://www.instagram.com/",
      label: "LinkedIn",
    },
    {
      Icon: <FiMail />,
      href: "",
      label: "Mail",
    },
  ];

  return (
    <html lang="en">
      <body className={"l-body " + inter.className}>
        <section className="fixed top-0 z-50 w-full">
          <Header />
        </section>

        <main className="l-main">{children}</main>

        <footer className="flex gap-8 p-6 text-foreground l-footer">
          <section
            data-cy="social-links"
            className="flex flex-wrap gap-5 pr-8 border-r border-white"
          >
            {socialLinks.map(({ Icon, href, label }) => (
              <Link
                key={label}
                href={href}
                className="w-[1.5rem] min-w-[24px] min-h-[24px] flex items-center justify-center"
              >
                {Icon}
              </Link>
            ))}
          </section>

          <article>
            <p>Noroff Education AS Tordenskjoldsgate 4 4612 Kristiansand</p>
            <p>+47 38 00 00 00</p>
          </article>
        </footer>
      </body>
    </html>
  );
}
